// Contract five's TypeScript side of the cross-language handshake
// (ADR-0086): the DB-native golden (regenerated by
// ingestion/regen_gamelog_golden.py, never golden:regen) must strict-parse,
// and the schema's receipt identity must actually bite.

import { readFileSync } from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'vitest'
import { parseGameLogPayload, shotPrices } from './gameLogPayload'

const golden = () =>
  JSON.parse(
    readFileSync(path.resolve(process.cwd(), 'tests/fixtures/gamelog.golden.json'), 'utf-8'),
  ) as ReturnType<typeof parseGameLogPayload>

describe('game-log payload schema', () => {
  it('strict-parses the committed golden', () => {
    const payload = parseGameLogPayload(golden())
    expect(payload._meta.totalGames).toBe(payload.games.length)
    expect(payload.games.length).toBeGreaterThan(0)
  })

  it('rejects an unknown key (strict contract)', () => {
    const mutated = { ...golden(), extra: true }
    expect(() => parseGameLogPayload(mutated)).toThrow()
  })

  it('rejects a broken receipt identity', () => {
    const mutated = golden()
    mutated.games[0]!.box.pts += 1
    expect(() => parseGameLogPayload(mutated)).toThrow(/box points/)
  })

  it('rejects a free-throw line that does not reconcile', () => {
    const mutated = golden()
    mutated.games[0]!.box.fta += 1
    expect(() => parseGameLogPayload(mutated)).toThrow(/FTA does not reconcile/)
  })

  it('rejects a null assist on a non-conflict shot', () => {
    const mutated = golden()
    const shot = mutated.games[0]!.shots.find((s) => s.assist !== null)!
    shot.assist = null
    expect(() => parseGameLogPayload(mutated)).toThrow(/zone-point conflict/)
  })

  it('prices exactly the evaluation-consistent shots', () => {
    // The ADR-0019 boundary at game grain: heaves and conflicts never price.
    expect(shotPrices({ zone: 'Restricted Area', value: 2 })).toBe(true)
    expect(shotPrices({ zone: 'Above the Break 3', value: 3 })).toBe(true)
    expect(shotPrices({ zone: 'Backcourt', value: 3 })).toBe(false)
    expect(shotPrices({ zone: 'Above the Break 3', value: 2 })).toBe(false)
    expect(shotPrices({ zone: 'Mid-Range', value: 3 })).toBe(false)
  })
})
